"""Cardapio do delivery (~110 itens em 10 categorias).

Gerado automaticamente. Cada item tem: id, categoria, tipo, nome, descricao,
lojas (['A'] / ['B'] / ['A','B']). Pizzas tem 'tamanhos' e 'permite_meio_a_meio';
combos tem 'preco' e 'inclui'; demais tem 'preco'. Itens com janela de horario
tem 'disponivel_de'/'disponivel_ate' (ex.: cafe da manha 07:00-11:00).
"""

ITENS = [{'id': 'pz01',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Marguerita',
  'descricao': 'Molho de tomate, mussarela, tomate em rodelas, manjericao fresco e azeite.',
  'lojas': ['A'],
  'tamanhos': {'broto': 32.9, 'media': 45.9, 'grande': 58.9, 'familia': 69.9},
  'permite_meio_a_meio': True},
 {'id': 'pz02',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Calabresa',
  'descricao': 'Calabresa fatiada, cebola roxa, mussarela e oregano.',
  'lojas': ['A', 'B'],
  'tamanhos': {'broto': 33.9, 'media': 46.9, 'grande': 59.9, 'familia': 71.9},
  'permite_meio_a_meio': True},
 {'id': 'pz03',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Portuguesa',
  'descricao': 'Presunto, ovos, cebola, ervilha, mussarela e azeitonas.',
  'lojas': ['A'],
  'tamanhos': {'broto': 36.9, 'media': 49.9, 'grande': 63.9, 'familia': 75.9},
  'permite_meio_a_meio': True},
 {'id': 'pz04',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Frango com Catupiry',
  'descricao': 'Frango desfiado temperado, Catupiry cremoso e mussarela.',
  'lojas': ['A', 'B'],
  'tamanhos': {'broto': 37.9, 'media': 51.9, 'grande': 64.9, 'familia': 77.9},
  'permite_meio_a_meio': True},
 {'id': 'pz05',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Quatro Queijos',
  'descricao': 'Mussarela, provolone, parmesao e gorgonzola gratinados.',
  'lojas': ['A'],
  'tamanhos': {'broto': 38.9, 'media': 52.9, 'grande': 66.9, 'familia': 79.9},
  'permite_meio_a_meio': True},
 {'id': 'pz06',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Mussarela',
  'descricao': 'Molho de tomate, muita mussarela, azeitonas e oregano.',
  'lojas': ['A', 'B'],
  'tamanhos': {'broto': 31.9, 'media': 44.9, 'grande': 57.9, 'familia': 68.9},
  'permite_meio_a_meio': True},
 {'id': 'pz07',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Napolitana',
  'descricao': 'Mussarela, tomate, parmesao ralado, alho e manjericao.',
  'lojas': ['A'],
  'tamanhos': {'broto': 34.9, 'media': 47.9, 'grande': 60.9, 'familia': 72.9},
  'permite_meio_a_meio': True},
 {'id': 'pz08',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Pepperoni',
  'descricao': 'Fatias de pepperoni levemente crocantes sobre mussarela.',
  'lojas': ['A'],
  'tamanhos': {'broto': 37.9, 'media': 50.9, 'grande': 64.9, 'familia': 76.9},
  'permite_meio_a_meio': True},
 {'id': 'pz09',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Bacon',
  'descricao': 'Bacon crocante, mussarela, cebola e um toque de oregano.',
  'lojas': ['A', 'B'],
  'tamanhos': {'broto': 35.9, 'media': 48.9, 'grande': 62.9, 'familia': 74.9},
  'permite_meio_a_meio': True},
 {'id': 'pz10',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Toscana',
  'descricao': 'Calabresa moida, bacon, cebola, mussarela e oregano.',
  'lojas': ['A'],
  'tamanhos': {'broto': 36.9, 'media': 49.9, 'grande': 63.9, 'familia': 75.9},
  'permite_meio_a_meio': True},
 {'id': 'pz11',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Lombo com Catupiry',
  'descricao': 'Lombo canadense, Catupiry, cebola e mussarela.',
  'lojas': ['A'],
  'tamanhos': {'broto': 38.9, 'media': 52.9, 'grande': 66.9, 'familia': 79.9},
  'permite_meio_a_meio': True},
 {'id': 'pz12',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Atum',
  'descricao': 'Atum, cebola roxa, mussarela e azeitonas.',
  'lojas': ['A'],
  'tamanhos': {'broto': 37.9, 'media': 51.9, 'grande': 65.9, 'familia': 78.9},
  'permite_meio_a_meio': True},
 {'id': 'pz13',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Vegetariana',
  'descricao': 'Brocolis, palmito, tomate, cebola, pimentao e mussarela.',
  'lojas': ['A'],
  'tamanhos': {'broto': 36.9, 'media': 49.9, 'grande': 63.9, 'familia': 75.9},
  'permite_meio_a_meio': True},
 {'id': 'pz14',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Palmito',
  'descricao': 'Palmito em rodelas, mussarela, tomate e oregano.',
  'lojas': ['A'],
  'tamanhos': {'broto': 36.9, 'media': 50.9, 'grande': 64.9, 'familia': 76.9},
  'permite_meio_a_meio': True},
 {'id': 'pz15',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Milho com Bacon',
  'descricao': 'Milho verde, bacon crocante, mussarela e cebolinha.',
  'lojas': ['A', 'B'],
  'tamanhos': {'broto': 35.9, 'media': 48.9, 'grande': 62.9, 'familia': 73.9},
  'permite_meio_a_meio': True},
 {'id': 'pz16',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Baiana',
  'descricao': 'Calabresa moida apimentada, ovos, cebola e mussarela.',
  'lojas': ['A'],
  'tamanhos': {'broto': 35.9, 'media': 48.9, 'grande': 61.9, 'familia': 73.9},
  'permite_meio_a_meio': True},
 {'id': 'pz17',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Camarao com Catupiry',
  'descricao': 'Camarao ao alho, Catupiry, mussarela e cheiro-verde.',
  'lojas': ['A'],
  'tamanhos': {'broto': 44.9, 'media': 58.9, 'grande': 74.9, 'familia': 89.9},
  'permite_meio_a_meio': True},
 {'id': 'pz18',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Escarola com Bacon',
  'descricao': 'Escarola refogada no alho, bacon, mussarela e azeitonas.',
  'lojas': ['A'],
  'tamanhos': {'broto': 36.9, 'media': 50.9, 'grande': 64.9, 'familia': 76.9},
  'permite_meio_a_meio': True},
 {'id': 'pz19',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Brocolis com Catupiry',
  'descricao': 'Brocolis no alho, Catupiry, bacon e mussarela.',
  'lojas': ['A'],
  'tamanhos': {'broto': 37.9, 'media': 51.9, 'grande': 65.9, 'familia': 78.9},
  'permite_meio_a_meio': True},
 {'id': 'pz20',
  'categoria': 'pizzas',
  'tipo': 'pizza',
  'nome': 'Rucula com Tomate Seco',
  'descricao': 'Mussarela, rucula fresca, tomate seco e lascas de parmesao.',
  'lojas': ['A'],
  'tamanhos': {'broto': 38.9, 'media': 52.9, 'grande': 67.9, 'familia': 80.9},
  'permite_meio_a_meio': True},
 {'id': 'hb01',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Classico da Casa',
  'descricao': 'Blend bovino 160g, queijo prato, alface, tomate e maionese da casa no pao brioche.',
  'lojas': ['A', 'B'],
  'preco': 26.9},
 {'id': 'hb02',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Cheddar Bacon',
  'descricao': 'Hamburguer 160g, cheddar cremoso e bacon crocante no pao australiano.',
  'lojas': ['A', 'B'],
  'preco': 32.9},
 {'id': 'hb03',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Duplo Smash',
  'descricao': 'Dois smash burgers, dobro de cheddar, picles e molho especial.',
  'lojas': ['A', 'B'],
  'preco': 34.9},
 {'id': 'hb04',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Bacon Supreme',
  'descricao': 'Blend 180g, muito bacon, cebola caramelizada e cheddar no pao brioche.',
  'lojas': ['A', 'B'],
  'preco': 35.9},
 {'id': 'hb05',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Veggie Grao-de-Bico',
  'descricao': 'Burger de grao-de-bico, alface, tomate, cebola roxa e maionese vegana.',
  'lojas': ['A', 'B'],
  'preco': 28.9},
 {'id': 'hb06',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Cheeseburger Duplo',
  'descricao': 'Dois blends 120g, dobro de queijo prato, picles e mostarda.',
  'lojas': ['A', 'B'],
  'preco': 33.9},
 {'id': 'hb07',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Barbecue Onion',
  'descricao': 'Blend 160g, molho barbecue, aneis de cebola empanados e cheddar.',
  'lojas': ['A', 'B'],
  'preco': 33.9},
 {'id': 'hb08',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Cheddar Melt',
  'descricao': 'Blend 160g, cheddar duplo derretido e cebola grelhada no pao de brioche.',
  'lojas': ['A', 'B'],
  'preco': 30.9},
 {'id': 'hb09',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Frango Crocante',
  'descricao': 'File de frango empanado, alface americana, tomate e maionese de alho.',
  'lojas': ['A', 'B'],
  'preco': 29.9},
 {'id': 'hb10',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Picante Jalapeno',
  'descricao': 'Blend 160g, pepper jack, jalapeno, bacon e molho chipotle apimentado.',
  'lojas': ['B'],
  'preco': 34.9},
 {'id': 'hb11',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Cogumelos e Gruyere',
  'descricao': 'Blend 160g, mix de cogumelos salteados e queijo gruyere derretido.',
  'lojas': ['B'],
  'preco': 37.9},
 {'id': 'hb12',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Costela Defumada',
  'descricao': 'Burger de costela desfiada, cebola crispy, cheddar e barbecue defumado.',
  'lojas': ['B'],
  'preco': 38.9},
 {'id': 'hb13',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Veggie Cogumelo Portobello',
  'descricao': 'Portobello grelhado, queijo, rucula, tomate seco e pesto no pao integral.',
  'lojas': ['B'],
  'preco': 31.9},
 {'id': 'hb14',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Triplo Monster',
  'descricao': 'Tres blends 120g, cheddar, bacon e cebola caramelizada empilhados.',
  'lojas': ['B'],
  'preco': 41.9},
 {'id': 'hb15',
  'categoria': 'hamburgueres',
  'tipo': 'simples',
  'nome': 'Salada Fit',
  'descricao': 'Blend magro 150g, mix de folhas, tomate, cenoura e molho leve de iogurte.',
  'lojas': ['A', 'B'],
  'preco': 24.9},
 {'id': 'cb01',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo Pizza da Meia-Noite',
  'descricao': 'Pizza grande de calabresa com cebola e muçarela, borda recheada de catupiry.',
  'lojas': ['A'],
  'preco': 74.9,
  'inclui': ['1 pizza grande de calabresa', '1 refrigerante 2L', '1 borda recheada de catupiry']},
 {'id': 'cb02',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo Casal Italiano',
  'descricao': 'Espaguete ao molho bolonhesa com parmesão e pão de alho artesanal.',
  'lojas': ['A'],
  'preco': 89.9,
  'inclui': ['1 espaguete à bolonhesa (2 pessoas)',
             '1 porção de pão de alho',
             '2 taças de suco de uva integral']},
 {'id': 'cb03',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo Sushi Duo',
  'descricao': 'Combinado japonês com salmão fresco, uramaki e temaki cremoso.',
  'lojas': ['A'],
  'preco': 98.5,
  'inclui': ['16 peças de sushi variado', '1 temaki de salmão', '1 porção de guioza']},
 {'id': 'cb04',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo Noite Napolitana',
  'descricao': 'Pizza margherita com tomate, manjericão e azeite, mais calzone de presunto.',
  'lojas': ['A'],
  'preco': 82,
  'inclui': ['1 pizza média margherita', '1 calzone de presunto e queijo', '1 refrigerante lata']},
 {'id': 'cb05',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo X-Bacon Completo',
  'descricao': 'Hambúrguer artesanal 180g com bacon crocante, cheddar e molho da casa.',
  'lojas': ['B'],
  'preco': 42.9,
  'inclui': ['1 X-Bacon 180g', '1 batata frita média', '1 refrigerante lata']},
 {'id': 'cb06',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo Café da Manhã Americano',
  'descricao': 'Ovos mexidos, bacon, panqueca com mel e pão na chapa.',
  'lojas': ['B'],
  'preco': 36.5,
  'inclui': ['1 prato de ovos com bacon', '2 panquecas com mel', '1 suco de laranja natural']},
 {'id': 'cb07',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo Executivo do Almoço',
  'descricao': 'Burger de costela desfiada com cebola caramelizada e queijo prato.',
  'lojas': ['B'],
  'preco': 45.9,
  'inclui': ['1 burger de costela', '1 batata rústica', '1 refrigerante lata', '1 mini brownie']},
 {'id': 'cb08',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo Família Burger',
  'descricao': 'Quatro cheeseburgers suculentos com muçarela e molho especial para dividir.',
  'lojas': ['B'],
  'preco': 119.9,
  'inclui': ['4 cheeseburgers', '1 batata frita família', '1 refrigerante 2L', '4 mini milkshakes']},
 {'id': 'cb09',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo Kids Feliz',
  'descricao': 'Mini hambúrguer com queijo, batata palito e sobremesa gelada.',
  'lojas': ['B'],
  'preco': 29.9,
  'inclui': ['1 mini hambúrguer', '1 batata palito pequena', '1 suco de caixinha', '1 sorvete de baunilha']},
 {'id': 'cb10',
  'categoria': 'combos',
  'tipo': 'combo',
  'nome': 'Combo Duo da Casa',
  'descricao': 'Escolha entre pizza broto ou burger clássico, sempre com sobremesa da casa.',
  'lojas': ['A', 'B'],
  'preco': 54.9,
  'inclui': ['1 pizza broto ou 1 burger clássico',
             '1 batata ou porção de fritas',
             '1 refrigerante lata',
             '1 petit gateau']},
 {'id': 'bb01',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Coca-Cola Lata 350ml',
  'descricao': 'Refrigerante de cola gelado, gaseificado e refrescante',
  'lojas': ['A', 'B'],
  'preco': 6.5},
 {'id': 'bb02',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Coca-Cola Zero Lata 350ml',
  'descricao': 'Cola sem acucar, sabor classico e bem gelada',
  'lojas': ['A', 'B'],
  'preco': 6.5},
 {'id': 'bb03',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Guarana Antarctica 600ml',
  'descricao': 'Refrigerante de guarana da Amazonia, doce e gaseificado',
  'lojas': ['A', 'B'],
  'preco': 9.9},
 {'id': 'bb04',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Coca-Cola 2L',
  'descricao': 'Garrafa familia de cola gelada para compartilhar',
  'lojas': ['A', 'B'],
  'preco': 14.9},
 {'id': 'bb05',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Suco Natural de Laranja 500ml',
  'descricao': 'Laranja pera espremida na hora, sem acucar adicionado',
  'lojas': ['A', 'B'],
  'preco': 13.9},
 {'id': 'bb06',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Suco Verde Detox 500ml',
  'descricao': 'Couve, maca verde, limao e gengibre batidos na hora',
  'lojas': ['A', 'B'],
  'preco': 15.9},
 {'id': 'bb07',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Limonada Suica 500ml',
  'descricao': 'Limao taiti batido com casca, gelo e leite condensado',
  'lojas': ['A', 'B'],
  'preco': 12.9},
 {'id': 'bb08',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Agua Mineral sem Gas 500ml',
  'descricao': 'Agua mineral natural pura e gelada',
  'lojas': ['A', 'B'],
  'preco': 5},
 {'id': 'bb09',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Agua com Gas 500ml',
  'descricao': 'Agua mineral gaseificada, leve e refrescante',
  'lojas': ['A', 'B'],
  'preco': 5.5},
 {'id': 'bb10',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Heineken Long Neck 330ml',
  'descricao': 'Cerveja puro malte holandesa, encorpada e gelada',
  'lojas': ['A', 'B'],
  'preco': 11.9},
 {'id': 'bb11',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Stella Artois Long Neck 330ml',
  'descricao': 'Lager premium belga, amargor equilibrado e refrescante',
  'lojas': ['A', 'B'],
  'preco': 11.9},
 {'id': 'bb12',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Chopp Brahma Garrafa 600ml',
  'descricao': 'Cerveja pilsen leve e cremosa, ideal para dividir',
  'lojas': ['A', 'B'],
  'preco': 13.9},
 {'id': 'bb13',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Milkshake de Chocolate 400ml',
  'descricao': 'Sorvete cremoso de chocolate batido com leite e calda',
  'lojas': ['B'],
  'preco': 18.9},
 {'id': 'bb14',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Milkshake de Morango 400ml',
  'descricao': 'Sorvete de baunilha batido com morangos frescos e calda',
  'lojas': ['B'],
  'preco': 18.9},
 {'id': 'bb15',
  'categoria': 'bebidas',
  'tipo': 'simples',
  'nome': 'Fanta Laranja Lata 350ml',
  'descricao': 'Refrigerante de laranja, doce, citrico e bem gelado',
  'lojas': ['A', 'B'],
  'preco': 6.5},
 {'id': 'sb01',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Tiramisù Classico',
  'descricao': 'Camadas de biscoito champagne embebido em café, creme de mascarpone e cacau em pó.',
  'lojas': ['A'],
  'preco': 22.9},
 {'id': 'sb02',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Panna Cotta de Frutas Vermelhas',
  'descricao': 'Creme italiano gelado de baunilha com calda de morango, framboesa e amora.',
  'lojas': ['A'],
  'preco': 18.5},
 {'id': 'sb03',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Cannoli Siciliano',
  'descricao': 'Massa crocante recheada com ricota doce, gotas de chocolate e pistache.',
  'lojas': ['A'],
  'preco': 19.9},
 {'id': 'sb04',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Mochi de Sorvete Sortido',
  'descricao': 'Bolinhos de arroz japoneses gelados recheados com sorvete de matchá, manga e morango.',
  'lojas': ['A'],
  'preco': 24},
 {'id': 'sb05',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Tempurá de Sorvete',
  'descricao': 'Sorvete de creme empanado e frito, quente por fora e gelado por dentro, com calda de '
               'chocolate.',
  'lojas': ['A'],
  'preco': 26.9},
 {'id': 'sb06',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Brownie com Sorvete',
  'descricao': 'Brownie de chocolate meio amargo com nozes, bola de sorvete de creme e calda quente.',
  'lojas': ['B'],
  'preco': 21.9},
 {'id': 'sb07',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Petit Gâteau de Chocolate',
  'descricao': 'Bolinho quente com recheio cremoso de chocolate belga e sorvete de baunilha.',
  'lojas': ['B'],
  'preco': 23.5},
 {'id': 'sb08',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Cheesecake de Frutas Vermelhas',
  'descricao': 'Base crocante de biscoito, creme de cream cheese e cobertura de geleia de frutas vermelhas.',
  'lojas': ['B'],
  'preco': 20.9},
 {'id': 'sb09',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Milkshake de Ovomaltine',
  'descricao': 'Shake cremoso de sorvete de baunilha batido com Ovomaltine e chantilly.',
  'lojas': ['B'],
  'preco': 17.9},
 {'id': 'sb10',
  'categoria': 'sobremesas',
  'tipo': 'simples',
  'nome': 'Cookie Recheado com Nutella',
  'descricao': 'Cookie grande e macio de gotas de chocolate com recheio derretido de Nutella.',
  'lojas': ['B'],
  'preco': 14.9},
 {'id': 'pr01',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Batata Frita Rustica',
  'descricao': 'Batatas fritas crocantes com casca, salpicadas com sal grosso e alecrim.',
  'lojas': ['A', 'B'],
  'preco': 24.9},
 {'id': 'pr02',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Onion Rings Empanados',
  'descricao': 'Aneis de cebola dourados e crocantes, empanados na farinha panko.',
  'lojas': ['A', 'B'],
  'preco': 26.9},
 {'id': 'pr03',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Iscas de Frango Crocantes',
  'descricao': 'Tiras de frango empanadas e fritas, servidas com molho barbecue.',
  'lojas': ['A', 'B'],
  'preco': 32.9},
 {'id': 'pr04',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Calabresa Acebolada',
  'descricao': 'Rodelas de calabresa artesanal salteadas com cebola roxa e pimentao.',
  'lojas': ['A', 'B'],
  'preco': 29.9},
 {'id': 'pr05',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Batata com Cheddar e Bacon',
  'descricao': 'Batatas fritas cobertas com cheddar cremoso e bacon crocante.',
  'lojas': ['A', 'B'],
  'preco': 34.9},
 {'id': 'pr06',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Bolinho de Bacalhau',
  'descricao': 'Bolinhos dourados de bacalhau desfiado com batata e salsinha.',
  'lojas': ['A'],
  'preco': 36.9},
 {'id': 'pr07',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Dadinho de Tapioca',
  'descricao': 'Cubos crocantes de tapioca com queijo coalho e geleia de pimenta.',
  'lojas': ['A', 'B'],
  'preco': 28.9},
 {'id': 'pr08',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Polenta Frita',
  'descricao': 'Palitos de polenta cremosa por dentro e crocante por fora, com parmesao.',
  'lojas': ['A'],
  'preco': 22.9},
 {'id': 'pr09',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Nuggets Caseiros',
  'descricao': 'Nuggets de frango empanados na hora, servidos com molho mostarda e mel.',
  'lojas': ['B'],
  'preco': 27.9},
 {'id': 'pr10',
  'categoria': 'porcoes',
  'tipo': 'simples',
  'nome': 'Mandioca Frita com Aioli',
  'descricao': 'Mandioca cozida e frita ate ficar crocante, acompanha aioli de alho.',
  'lojas': ['A', 'B'],
  'preco': 23.9},
 {'id': 'ms01',
  'categoria': 'massas',
  'tipo': 'simples',
  'nome': 'Spaghetti alla Carbonara',
  'descricao': 'Spaghetti com guanciale crocante, gema, pecorino e pimenta-do-reino.',
  'lojas': ['A'],
  'preco': 42.9},
 {'id': 'ms02',
  'categoria': 'massas',
  'tipo': 'simples',
  'nome': 'Lasanha a Bolonhesa',
  'descricao': 'Camadas de massa fresca, ragu de carne, bechamel e parmesao gratinado.',
  'lojas': ['A'],
  'preco': 48.9},
 {'id': 'ms03',
  'categoria': 'massas',
  'tipo': 'simples',
  'nome': 'Nhoque ao Sugo',
  'descricao': 'Nhoque de batata artesanal ao molho de tomate italiano e manjericao.',
  'lojas': ['A'],
  'preco': 39.9},
 {'id': 'ms04',
  'categoria': 'massas',
  'tipo': 'simples',
  'nome': 'Fettuccine Alfredo',
  'descricao': 'Fettuccine em creme de manteiga, parmesao e toque de noz-moscada.',
  'lojas': ['A'],
  'preco': 44.9},
 {'id': 'ms05',
  'categoria': 'massas',
  'tipo': 'simples',
  'nome': 'Penne ao Funghi',
  'descricao': 'Penne com mix de cogumelos, creme de leite fresco e parmesao.',
  'lojas': ['A'],
  'preco': 45.9},
 {'id': 'ms06',
  'categoria': 'massas',
  'tipo': 'simples',
  'nome': 'Ravioli de Queijo com Manteiga e Salvia',
  'descricao': 'Ravioli recheado de queijos ao molho de manteiga aromatizada com salvia.',
  'lojas': ['A'],
  'preco': 49.9},
 {'id': 'ms07',
  'categoria': 'massas',
  'tipo': 'simples',
  'nome': 'Talharim ao Frutti di Mare',
  'descricao': 'Talharim com camarao, lula e mexilhoes ao molho de tomate e vinho branco.',
  'lojas': ['A'],
  'preco': 54.9},
 {'id': 'ms08',
  'categoria': 'massas',
  'tipo': 'simples',
  'nome': 'Spaghetti Aglio e Olio',
  'descricao': 'Spaghetti com alho dourado, azeite extravirgem, pimenta e salsinha.',
  'lojas': ['A'],
  'preco': 34.9},
 {'id': 'sl01',
  'categoria': 'saladas',
  'tipo': 'simples',
  'nome': 'Salada Caesar com Frango Grelhado',
  'descricao': 'Alface romana crocante, frango grelhado, croutons, lascas de parmesao e molho caesar '
               'cremoso.',
  'lojas': ['A', 'B'],
  'preco': 28.9},
 {'id': 'sl02',
  'categoria': 'saladas',
  'tipo': 'simples',
  'nome': 'Salada Caprese',
  'descricao': 'Tomate italiano, muçarela de bufala, manjericao fresco e fio de azeite extra virgem.',
  'lojas': ['A', 'B'],
  'preco': 26.5},
 {'id': 'sl03',
  'categoria': 'saladas',
  'tipo': 'simples',
  'nome': 'Salada Tropical de Frango',
  'descricao': 'Mix de folhas, frango desfiado, abacaxi, manga, castanha de caju e molho de iogurte.',
  'lojas': ['A', 'B'],
  'preco': 24.9},
 {'id': 'sl04',
  'categoria': 'saladas',
  'tipo': 'simples',
  'nome': 'Salada Grega',
  'descricao': 'Pepino, tomate, cebola roxa, azeitonas pretas, queijo feta e oregano com azeite.',
  'lojas': ['A', 'B'],
  'preco': 25.9},
 {'id': 'sl05',
  'categoria': 'saladas',
  'tipo': 'simples',
  'nome': 'Salada de Rucula com Parma',
  'descricao': 'Rucula fresca, presunto parma, tomate seco, lascas de parmesao e reducao balsamica.',
  'lojas': ['A', 'B'],
  'preco': 32.9},
 {'id': 'sl06',
  'categoria': 'saladas',
  'tipo': 'simples',
  'nome': 'Salada Verde com Quinoa',
  'descricao': 'Folhas verdes, quinoa, grao-de-bico, abacate, tomate cereja e vinagrete de limao.',
  'lojas': ['A', 'B'],
  'preco': 23.5},
 {'id': 'cf01',
  'categoria': 'cafe_da_manha',
  'tipo': 'simples',
  'nome': 'Pao na Chapa com Manteiga',
  'descricao': 'Pao frances quentinho na chapa com manteiga derretida',
  'lojas': ['B'],
  'disponivel_de': '07:00',
  'disponivel_ate': '11:00',
  'preco': 7.5},
 {'id': 'cf02',
  'categoria': 'cafe_da_manha',
  'tipo': 'simples',
  'nome': 'Tapioca de Queijo Coalho',
  'descricao': 'Tapioca fininha recheada com queijo coalho dourado',
  'lojas': ['B'],
  'disponivel_de': '07:00',
  'disponivel_ate': '11:00',
  'preco': 12},
 {'id': 'cf03',
  'categoria': 'cafe_da_manha',
  'tipo': 'simples',
  'nome': 'Misto Quente na Chapa',
  'descricao': 'Pao de forma com presunto e queijo derretido na chapa',
  'lojas': ['B'],
  'disponivel_de': '07:00',
  'disponivel_ate': '11:00',
  'preco': 10.5},
 {'id': 'cf04',
  'categoria': 'cafe_da_manha',
  'tipo': 'simples',
  'nome': 'Cappuccino Cremoso',
  'descricao': 'Espresso encorpado com leite vaporizado e canela',
  'lojas': ['B'],
  'disponivel_de': '07:00',
  'disponivel_ate': '11:00',
  'preco': 9},
 {'id': 'cf05',
  'categoria': 'cafe_da_manha',
  'tipo': 'simples',
  'nome': 'Ovos Mexidos na Manteiga',
  'descricao': 'Ovos cremosos mexidos na manteiga com cebolinha',
  'lojas': ['B'],
  'disponivel_de': '07:00',
  'disponivel_ate': '11:00',
  'preco': 11},
 {'id': 'cf06',
  'categoria': 'cafe_da_manha',
  'tipo': 'simples',
  'nome': 'Pao de Queijo Mineiro',
  'descricao': 'Porcao de paes de queijo quentinhos e macios',
  'lojas': ['B'],
  'disponivel_de': '07:00',
  'disponivel_ate': '11:00',
  'preco': 8.5},
 {'id': 'cf07',
  'categoria': 'cafe_da_manha',
  'tipo': 'simples',
  'nome': 'Omelete de Presunto e Queijo',
  'descricao': 'Omelete fofinho recheado com presunto e queijo',
  'lojas': ['B'],
  'disponivel_de': '07:00',
  'disponivel_ate': '11:00',
  'preco': 14},
 {'id': 'cf08',
  'categoria': 'cafe_da_manha',
  'tipo': 'simples',
  'nome': 'Tapioca de Frango com Catupiry',
  'descricao': 'Tapioca recheada com frango desfiado e catupiry',
  'lojas': ['B'],
  'disponivel_de': '07:00',
  'disponivel_ate': '11:00',
  'preco': 16},
 {'id': 'jp01',
  'categoria': 'japonesa',
  'tipo': 'simples',
  'nome': 'Temaki Filadélfia',
  'descricao': 'Cone de alga crocante recheado com salmão fresco, cream cheese e cebolinha.',
  'lojas': ['A'],
  'preco': 32},
 {'id': 'jp02',
  'categoria': 'japonesa',
  'tipo': 'simples',
  'nome': 'Uramaki Skin',
  'descricao': 'Oito peças com pele de salmão crocante, cream cheese e cebolinha, finalizadas com tarê.',
  'lojas': ['A'],
  'preco': 29.9},
 {'id': 'jp03',
  'categoria': 'japonesa',
  'tipo': 'simples',
  'nome': 'Combinado Central 20 Peças',
  'descricao': 'Seleção variada de niguiris, sashimis de salmão e uramakis Filadélfia.',
  'lojas': ['A'],
  'preco': 59.9},
 {'id': 'jp04',
  'categoria': 'japonesa',
  'tipo': 'simples',
  'nome': 'Hot Roll de Salmão',
  'descricao': 'Enrolado empanado e frito na hora, com salmão, cream cheese e molho tarê.',
  'lojas': ['A'],
  'preco': 34.9},
 {'id': 'jp05',
  'categoria': 'japonesa',
  'tipo': 'simples',
  'nome': 'Guioza da Casa (6 un.)',
  'descricao': 'Pastéis japoneses grelhados recheados de carne suína e gengibre, com shoyu agridoce.',
  'lojas': ['A'],
  'preco': 26.5},
 {'id': 'jp06',
  'categoria': 'japonesa',
  'tipo': 'simples',
  'nome': 'Temaki de Atum Picante',
  'descricao': 'Atum fresco em cubos com maionese apimentada, cream cheese e cebolinha.',
  'lojas': ['A'],
  'preco': 36},
 {'id': 'jp07',
  'categoria': 'japonesa',
  'tipo': 'simples',
  'nome': 'Uramaki Ebi Furai',
  'descricao': 'Camarão empanado crocante, cream cheese e pepino, cobertos com gergelim.',
  'lojas': ['A'],
  'preco': 38.9},
 {'id': 'jp08',
  'categoria': 'japonesa',
  'tipo': 'simples',
  'nome': 'Sashimi de Salmão (10 fatias)',
  'descricao': 'Fatias generosas de salmão fresco, servidas com shoyu, wasabi e gengibre.',
  'lojas': ['A'],
  'preco': 42}]
